# Generated by Django 5.2.7 on 2026-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_groups_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
