# Generated by Django 5.2.7 on 2026-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_birth_date_customuser_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_password_change',
            field=models.BooleanField(default=True, verbose_name='Requiere Cambio de Contraseña'),
        ),
    ]
