# Generated by Django 5.2.7 on 2026-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_requires_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Segundo Nombre'),
        ),
    ]
