# Generated by Django 5.2.7 on 2026-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil'),
        ),
    ]
