# Generated by Django 5.2.7 on 2026-03-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Dueño)'), ('VENDEDOR', 'Vendedor'), ('LOGISTICA', 'Logística'), ('CONDUCTOR', 'Conductor'), ('GUIA', 'Guía'), ('DESARROLLADOR', 'Desarrollador')], default='VENDEDOR', max_length=20),
        ),
    ]
