# Generated by Django 5.2.7 on 2026-02-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tour_cancellation_policy_tour_description_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepassenger',
            name='sale',
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venta / Reserva', 'verbose_name_plural': 'Ventas / Reservas'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cliente_principal',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='estado_venta',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='moneda_pago',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sobrecupo',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='voucher',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_name',
            field=models.CharField(default='Cliente', max_length=200, verbose_name='Nombre Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_rut_passport',
            field=models.CharField(default='00000000', max_length=50, verbose_name='RUT/Pasaporte'),
        ),
        migrations.AddField(
            model_name='sale',
            name='hotel_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hotel/Dirección de Recogida'),
        ),
        migrations.AddField(
            model_name='sale',
            name='passengers_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Pasajeros'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABONADO', 'Abonado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20, verbose_name='Estado Pago'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total a Pagar'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalog.tour'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tour_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Tour'),
        ),
        migrations.AddField(
            model_name='sale',
            name='voucher_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/%Y/%m/', verbose_name='Comprobante'),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rut_passport', models.CharField(blank=True, max_length=50)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='sales.sale')),
            ],
            options={
                'db_table': 'sales_passenger',
            },
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
        migrations.DeleteModel(
            name='SalePassenger',
        ),
    ]
