# Generated by Django 5.2.7 on 2026-02-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salepassenger_sale_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Pesos Chilenos'), ('USD', 'Dólares'), ('BRL', 'Reales Brasileños')], default='CLP', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Tipo de Cambio'),
        ),
        migrations.AddField(
            model_name='sale',
            name='private_trip_description',
            field=models.TextField(blank=True, verbose_name='Descripción del viaje (Privado)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='private_trip_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones (Privado)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de Aprobación'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20, verbose_name='Estado de Venta'),
        ),
    ]
