# Generated by Django 5.2.7 on 2026-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_currency_sale_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='¿Es Venta Privada?'),
        ),
    ]
