# Generated by Django 5.2.7 on 2026-02-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(default='Chilena', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_nationality',
            field=models.CharField(default='Chilena', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tour_language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('PT', 'Portugués')], default='ES', max_length=2, verbose_name='Idioma del Tour'),
        ),
    ]
