# Generated by Django 5.2.7 on 2026-02-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_passenger_name_remove_sale_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(choices=[('Chilena', 'Chilena'), ('Brasileña', 'Brasileña'), ('Estadounidense', 'Estadounidense'), ('Argentina', 'Argentina'), ('Peruana', 'Peruana'), ('Boliviana', 'Boliviana'), ('Colombiana', 'Colombiana'), ('Uruguaya', 'Uruguaya'), ('Paraguaya', 'Paraguaya'), ('Otra', 'Otra')], default='Chilena', max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_nationality',
            field=models.CharField(choices=[('Chilena', 'Chilena'), ('Brasileña', 'Brasileña'), ('Estadounidense', 'Estadounidense'), ('Argentina', 'Argentina'), ('Peruana', 'Peruana'), ('Boliviana', 'Boliviana'), ('Colombiana', 'Colombiana'), ('Uruguaya', 'Uruguaya'), ('Paraguaya', 'Paraguaya'), ('Otra', 'Otra')], default='Chilena', max_length=50, verbose_name='Nacionalidad'),
        ),
    ]
