# Generated by Django 5.2.7 on 2026-02-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('sales', '0006_alter_passenger_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales', to='logistics.vehicle', verbose_name='Vehículo / Agencia Asignada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='logistics_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Logística (Internas)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Recogida'),
        ),
    ]
