# Generated by Django 5.2.7 on 2026-02-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tour_cancellation_policy_tour_description_and_more'),
        ('sales', '0007_sale_assigned_vehicle_sale_logistics_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('tour_language', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('PT', 'Portugués')], default='ES', max_length=2, verbose_name='Idioma')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privado')),
                ('private_description', models.TextField(blank=True, verbose_name='Descripción privada')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_stops', to='sales.sale')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Destino de Venta',
                'verbose_name_plural': 'Destinos de Venta',
                'db_table': 'sales_sale_tour',
                'ordering': ['order', 'id'],
            },
        ),
    ]
