# Generated by Django 5.2.7 on 2026-02-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saletour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='voucher_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/%Y/%m/', verbose_name='Comprobante 2'),
        ),
        migrations.AddField(
            model_name='sale',
            name='voucher_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/%Y/%m/', verbose_name='Comprobante 3'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='voucher_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/%Y/%m/', verbose_name='Comprobante 1'),
        ),
    ]
