# Generated by Django 5.2.7 on 2026-02-25 19:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicaltour'),
        ('logistics', '0001_initial'),
        ('sales', '0009_sale_voucher_image_2_sale_voucher_image_3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_first_name', models.CharField(default='', max_length=100, verbose_name='Nombres Cliente')),
                ('client_last_name', models.CharField(default='', max_length=100, verbose_name='Apellidos Cliente')),
                ('client_rut_passport', models.CharField(default='00000000', max_length=50, verbose_name='RUT/Pasaporte')),
                ('client_nationality', models.CharField(choices=[('Chilena', 'Chilena'), ('Brasileña', 'Brasileña'), ('Estadounidense', 'Estadounidense'), ('Argentina', 'Argentina'), ('Peruana', 'Peruana'), ('Boliviana', 'Boliviana'), ('Colombiana', 'Colombiana'), ('Uruguaya', 'Uruguaya'), ('Paraguaya', 'Paraguaya'), ('Otra', 'Otra')], default='Chilena', max_length=50, verbose_name='Nacionalidad')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('client_phone', models.CharField(default='', max_length=50, verbose_name='Teléfono')),
                ('hotel_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Hotel/Dirección de Recogida')),
                ('is_private', models.BooleanField(default=False, verbose_name='¿Es Venta Privada?')),
                ('tour_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Tour')),
                ('tour_language', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('PT', 'Portugués')], default='ES', max_length=2, verbose_name='Idioma del Tour')),
                ('passengers_count', models.PositiveIntegerField(default=1, verbose_name='Cantidad Pasajeros')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total a Pagar')),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('currency', models.CharField(choices=[('CLP', 'Pesos Chilenos'), ('USD', 'Dólares'), ('BRL', 'Reales Brasileños')], default='CLP', max_length=10, verbose_name='Moneda')),
                ('payment_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABONADO', 'Abonado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20, verbose_name='Estado Pago')),
                ('status', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de Aprobación'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20, verbose_name='Estado de Venta')),
                ('voucher_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comprobante 1')),
                ('voucher_image_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comprobante 2')),
                ('voucher_image_3', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comprobante 3')),
                ('private_trip_description', models.TextField(blank=True, verbose_name='Descripción del viaje (Privado)')),
                ('private_trip_observations', models.TextField(blank=True, verbose_name='Observaciones (Privado)')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Recogida')),
                ('logistics_notes', models.TextField(blank=True, verbose_name='Notas de Logística (Internas)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.vehicle', verbose_name='Vehículo / Agencia Asignada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.tour')),
            ],
            options={
                'verbose_name': 'historical Venta / Reserva',
                'verbose_name_plural': 'historical Ventas / Reservas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
