# Generated by Django 5.2.7 on 2026-02-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_agency'),
        ('sales', '0010_historicalsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletour',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.agency', verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='origin_channel',
            field=models.CharField(choices=[('DIRECTO', 'Directo'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('AGENCIA', 'Agencia Externa'), ('OTRO', 'Otro')], default='DIRECTO', max_length=50, verbose_name='Origen de la Reserva'),
        ),
        migrations.AddField(
            model_name='sale',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.agency', verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='sale',
            name='origin_channel',
            field=models.CharField(choices=[('DIRECTO', 'Directo'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('AGENCIA', 'Agencia Externa'), ('OTRO', 'Otro')], default='DIRECTO', max_length=50, verbose_name='Origen de la Reserva'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='pax_adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Adultos'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='pax_infants',
            field=models.PositiveIntegerField(default=0, verbose_name='Infantes'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='price_adult',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Adulto'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='price_infant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Infante'),
        ),
    ]
