# Generated by Django 5.2.7 on 2026-03-01 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_saletour_unit_price_historicalsale_agency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='client_notified',
            field=models.BooleanField(default=False, verbose_name='Cliente Notificado'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='client_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificado el'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_notified',
            field=models.BooleanField(default=False, verbose_name='Cliente Notificado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificado el'),
        ),
        migrations.AddField(
            model_name='sale',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el'),
        ),
        migrations.AddField(
            model_name='sale',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations_made', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
