# Generated by Django 5.2.7 on 2026-03-03 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_add_confirmation_traceability_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saletour',
            name='stop_cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='stop_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado en'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='stop_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='stop_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12, verbose_name='Estado del Stop'),
        ),
    ]
