# Generated by Django 5.2.7 on 2026-03-03 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('sales', '0013_stop_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saletour',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_assignments', to='logistics.vehicle', verbose_name='Vehículo Asignado'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='logistics_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Logística (Internas)'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Recogida'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='vehicle_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vehículo asignado en'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='vehicle_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_vehicle_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
    ]
