# Generated by Django 5.2.7 on 2026-03-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_stop_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='client_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Edad'),
        ),
    ]
