# Generated by Django 5.2.7 on 2026-03-25 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_historicalsale_client_age_passenger_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saletour',
            name='attendance_observation',
            field=models.TextField(blank=True, verbose_name='Observación de Asistencia'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='attendance_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VIAJO', 'Viajó'), ('NO_VIAJO', 'No Viajó'), ('VIAJO_CON_OBS', 'Viajó con Observación')], default='PENDIENTE', max_length=20, verbose_name='Asistencia'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='attendance_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asistencia registrada el'),
        ),
        migrations.AddField(
            model_name='saletour',
            name='attendance_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Asistencia registrada por'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de Aprobación'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDIENTE', 'Pendiente de Aprobación'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de Venta'),
        ),
    ]
