# Generated by Django 5.2.7 on 2026-02-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cancellation_policy',
            field=models.TextField(default='Cancelación gratuita hasta 48 horas antes del inicio del tour.', verbose_name='Políticas de Cancelación'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción Corta (Empleados)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, help_text='Ej: 08 - 10 horas', max_length=100, verbose_name='Duración (aprox)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Foto Referencial 1'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Foto Referencial 2'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.TextField(blank=True, verbose_name='Incluye'),
        ),
        migrations.AddField(
            model_name='tour',
            name='languages',
            field=models.CharField(blank=True, help_text='Español, Inglés, etc.', max_length=255, verbose_name='Idiomas Disponibles'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_includes',
            field=models.TextField(blank=True, verbose_name='No Incluye'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.CharField(blank=True, max_length=200, verbose_name='Región de Origen'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='precio_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio BRL'),
        ),
    ]
