# Generated by Django 5.2.7 on 2026-02-25 19:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tour_cancellation_policy_tour_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTour',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tour_type', models.CharField(choices=[('REGULAR', 'Tour Regular'), ('PRIVADO', 'Tour Privado')], default='REGULAR', max_length=10)),
                ('precio_clp', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio BRL')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destino')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Región de Origen')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Corta (Empleados)')),
                ('includes', models.TextField(blank=True, verbose_name='Incluye')),
                ('not_includes', models.TextField(blank=True, verbose_name='No Incluye')),
                ('duration', models.CharField(blank=True, help_text='Ej: 08 - 10 horas', max_length=100, verbose_name='Duración (aprox)')),
                ('cancellation_policy', models.TextField(default='Cancelación gratuita hasta 48 horas antes del inicio del tour.', verbose_name='Políticas de Cancelación')),
                ('languages', models.CharField(blank=True, help_text='Español, Inglés, etc.', max_length=255, verbose_name='Idiomas Disponibles')),
                ('image_1', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto Referencial 1')),
                ('image_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto Referencial 2')),
                ('dias_operativos', models.CharField(default='1,2,3,4,5,6', help_text='Días que opera: 0=Dom, 1=Lun, ..., 6=Sab. Ej: 1,3,5 para Lun,Mie,Vie', max_length=50)),
                ('cupo_maximo_diario', models.PositiveIntegerField(default=20, help_text='Stock máximo por día')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tour',
                'verbose_name_plural': 'historical Tours',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
