# Generated by Django 5.2.7 on 2026-03-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicaltour'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltour',
            name='precio_adulto_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adulto BRL'),
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='precio_adulto_clp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Adulto CLP'),
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='precio_adulto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adulto USD'),
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='precio_infante_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Infante BRL'),
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='precio_infante_clp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Infante CLP'),
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='precio_infante_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Infante USD'),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adulto BRL'),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto_clp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Adulto CLP'),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Adulto USD'),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_infante_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Infante BRL'),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_infante_clp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Infante CLP'),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_infante_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Infante USD'),
        ),
        migrations.AlterField(
            model_name='historicaltour',
            name='precio_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base BRL'),
        ),
        migrations.AlterField(
            model_name='historicaltour',
            name='precio_clp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Base CLP'),
        ),
        migrations.AlterField(
            model_name='historicaltour',
            name='precio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base USD'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='precio_brl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base BRL'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='precio_clp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Base CLP'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='precio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base USD'),
        ),
    ]
