# Generated by Django 5.2.7 on 2026-03-05 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_email',
            field=models.CharField(blank=True, max_length=254, verbose_name='Email del Conductor (opcional)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre del Conductor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_phone',
            field=models.CharField(blank=True, help_text='Formato internacional. Ej: +56912345678', max_length=30, verbose_name='Teléfono / WhatsApp del Conductor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Observaciones sobre el vehículo (seguro, mantención, etc.)', verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=60, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('MINIVAN', 'Minivan'), ('BUS', 'Bus'), ('MICROBUS', 'Microbús'), ('VAN', 'Van / Furgón'), ('SUV', 'SUV / 4x4'), ('SEDAN', 'Sedan'), ('OTHER', 'Otro')], default='VAN', max_length=20, verbose_name='Tipo de Vehículo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año del Vehículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='default_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Conductor por Defecto (usuario del sistema)'),
        ),
    ]
