# Generated by Django 5.2.7 on 2026-03-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_vehicle_driver_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyoperation',
            options={'ordering': ['date', 'tour__name'], 'verbose_name': 'Operación Diaria (Grupo Viaje)', 'verbose_name_plural': 'Operaciones Diarias (Grupos Viaje)'},
        ),
        migrations.AlterUniqueTogether(
            name='dailyoperation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Check-in (Inicio Vaje)'),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='check_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_made', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Check-out (Fin Viaje)'),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='check_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_outs_made', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'GUIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guide_operations', to=settings.AUTH_USER_MODEL, verbose_name='Guía'),
        ),
        migrations.AddField(
            model_name='dailyoperation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_operations', to='logistics.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='dailyoperation',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver_operations', to=settings.AUTH_USER_MODEL, verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='dailyoperation',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado Operativo'),
        ),
    ]
