# Generated by Django 5.2.7 on 2026-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Agencia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'db_table': 'clients_agency',
                'ordering': ['name'],
            },
        ),
    ]
