# Generated by Django 5.2.7 on 2026-02-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_tour_cancellation_policy_tour_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('ADMIN', 'Administración'), ('LOGISTICA', 'Logística')], default='LOGISTICA', max_length=20, verbose_name='Dirigido a')),
                ('ticket_type', models.CharField(choices=[('SOBRECUPO', 'Solicitud de Sobrecupo'), ('CAMBIO', 'Solicitud de Cambio de Tour'), ('CONSULTA', 'Consulta General'), ('INCIDENCIA', 'Incidencia / Problema'), ('OTRO', 'Otro')], default='CONSULTA', max_length=20, verbose_name='Tipo de Solicitud')),
                ('title', models.CharField(max_length=200, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('tour_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Tour')),
                ('response', models.TextField(blank=True, default='', verbose_name='Respuesta')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='catalog.tour', verbose_name='Tour Relacionado')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets / Solicitudes',
                'ordering': ['-created_at'],
            },
        ),
    ]
